### PR TITLE
Remove course db function

### PR DESCRIPTION
**Pull request by DasilvaB**
Implemented the remove course db function for requirement 8.2:
https://github.com/smacademic/project-GEEKS/issues/12

The function takes the course Number and Title. It checks to make sure row does exist, if not it raises an exception. Otherwise it removes the row.

### CODE REVIEW

**Comment by DasilvaB** [comment]
I tried to figure out how to fix the issue where there are other commits here as well but I couldn't figure it out. I know Ken had this same issue, does anyone else know how to fix this?

**Review by kozlowskik — COMMENTED** [review]
Looks good, the only question I would have is would it be required by the end user to enter in both the Course Number **and** title to remove the course or could there be a way implemented where if only the number is entered and the title can be queried for?

**Comment by griffine** [comment]
I think the function looks good. I think it would be okay to implement as is, though depending on how the UI is implemented, the way that Ken has mentioned may work better. 

As for the extra commits showing up, I have made a separate issue ( #34 ) to address it.

**Review by fitz-cris — APPROVED** [review]
I agree with Ely, we can revisit the subject if the UI requires us to rethink our approach.

**Comment by DasilvaB** [comment]
Well I chose Number + Title because that's what the primary key relies on

**Review by kozlowskik — APPROVED** [review]

**Review by griffine — APPROVED** [review]

**Pull request merged**
